### ISSUE TITLE
Imposibile to set user ID

### ISSUE THREAD

**Issue by skynet** [nginxinc/nginx-amplify-agent#135] opened 2019-01-03 05:26 UTC
Regardless of agent.conf:

```
[nginx]
user = www
```

Agent is still running as nginx
```
# ps aux | grep amplify-agent
nginx    15291  0.3  0.5 261904 40432 ?        Sl   00:22   0:00 amplify-agent
```

**Comment by Humni** [comment] 2019-03-23 03:06
I'm having the same issue. the user directive is set inside the Nginx config also, but it's not changing the user which the amplifying agent is running as

**Comment by G00364778** [comment] 2019-03-23 19:01
Same issue here:

Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1034-aws x86_64)

root     26659  0.4  4.9 435744 24476 ?        Ss   18:44   0:00 php-fpm: master process (/etc/php/7.2/fpm/php-fpm.conf)
www-data 26679  0.0  2.6 438044 13028 ?        S    18:44   0:00 php-fpm: pool www
www-data 26680  0.0  2.6 438044 13032 ?        S    18:44   0:00 php-fpm: pool www
root     26699  0.0  0.3 141384  1704 ?        Ss   18:44   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
www-data 26703  0.0  1.3 143684  6512 ?        S    18:44   0:00 nginx: worker process
nginx    26768  0.0  4.4 237848 21984 ?        Sl   18:44   0:00 amplify-agent

not working as documented and no way to fix this as it stands.....

**Comment by joerecra** [comment] 2019-03-26 06:25
Same issue, any news ?

**Comment by aluttik** [comment] 2019-03-26 21:49
We're aware of the problem. The issue is that you can specify the user only if you're using the init script, not the systemd script. A solution is in the works but in the meantime that's something to consider.

**Comment by joerecra** [comment] 2019-03-26 22:06
@aluttik but what is the "out of the box" solution ? change to nginx for the nginx.conf user ? We need solution about this, and support mail doesnt work.

**Comment by Humni** [comment] 2019-03-27 02:57
@aluttik not to mention the problem only got worse when attempting to reinstall, the install fails as the agent is unable to run. If I get the time I'll dig into it deeper and open up a related issue for it

**Comment by defanator** [comment] 2019-03-27 10:32
@joerecra could you please let me know your email address you're using to contact support? (feel free to contact via ab at nginx dot com if you have a reason to not disclose it here)

**Comment by defanator** [comment] 2019-03-27 10:42
@skynet what OS are you on? what is your nginx-amplify-agent package version?

**Comment by petqa** [comment] 2019-03-27 16:37
good day, same problem.
CenOS 7.6, last package from your script

**Comment by joerecra** [comment] 2019-03-27 16:54
Good day @defanator , my email is joerecra at gmail dat com.

**Comment by kn007** [comment] 2019-03-28 05:13
Same issue here...

**Comment by kn007** [comment] 2019-03-28 11:47
fixed on 1.7.0-4, thx.

**Comment by joerecra** [comment] 2019-03-28 14:23
@kn007 but 1.7.0-4 has not been released ! lol, last release is 1.7.0-3, where is the new release ???? how do I upgrade it ?

**Comment by defanator** [comment] 2019-03-28 15:07
@joerecra 1.7.0-4 was released earlier today. You should clear your local metadata/cache and try to upgrade.

**Comment by defanator** [comment] 2019-03-28 15:07
@kn007 thanks for the confirmation!

**Comment by joerecra** [comment] 2019-03-28 15:51
@defanator fixed !

**Closed** 2019-03-28 15:52 UTC

**Comment by Humni** [comment] 2019-03-28 21:50
@defanator this fixed the re-install issue also. All is working well. Thank you for the quick fix!
