### ISSUE TITLE
nginx_metrics failed to collect AccessDenied

### ISSUE THREAD

**Issue by joerecra** [nginxinc/nginx-amplify-agent#141] opened 2019-03-26 05:42 UTC
Nginx metrics in graphs say "metrics unavailable" in Nginx Amplify web.

Looking in amplify-agent log I found multiple: nginx_metrics nginx_metrics failed to collect: workers raised AccessDenied.

Access.log and error.log are own from www-data, default user in nginx.conf. I reloaded many times nginx but doesnt work. And I added varibles for access and error in nginx.conf

Any help, please :+1:

**Comment by defanator** [comment] 2019-03-27 10:43
Duplicate of #135.

**Comment by defanator** [comment] 2019-03-28 15:52
Fixed with the 1.7.0-4 agent package release.

**Closed by defanator** 2019-03-28 15:52 UTC
